DROP TABLE IF EXISTS WATERING;

CREATE TABLE IF NOT EXISTS WATERING(
  ID            INTEGER   PRIMARY KEY,
  STARTED       TEXT  NOT NULL,
  ENDED         TEXT
);

DROP TABLE IF EXISTS SCHEDULE;

CREATE TABLE IF NOT EXISTS SCHEDULE(
  ID            INTEGER   PRIMARY KEY,
  MONDAY        INTEGER DEFAULT 1,
  TUESDAY       INTEGER DEFAULT 1,
  WEDNESDAY     INTEGER DEFAULT 1,
  THURSDAY      INTEGER DEFAULT 1,
  FRIDAY        INTEGER DEFAULT 1,
  SATURDAY      INTEGER DEFAULT 1,
  SUNDAY        INTEGER DEFAULT 1,
  TIME          TEXT NOT NULL,
  ACTIVE        INTEGER DEFAULT 1,
  DURATION      INTEGER NOT NULL
);

INSERT INTO SCHEDULE (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY, TIME, ACTIVE, DURATION) VALUES (1, 1, 1, 1, 1, 1, 1, "12:00", 1, 30);
INSERT INTO SCHEDULE (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY, TIME, ACTIVE, DURATION) VALUES (0, 0, 0, 0, 0, 0, 0, "08:00", 0, 15);