-- CREATE TABLE IF NOT EXISTS WEATHER(
--    ID           INTEGER   PRIMARY KEY,
--    FETCHED      TEXT  NOT NULL,
--    FOR_DATE     TEXT  NOT NULL,
--    TEMPERATURE  REAL  NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS MEASUREMENTS(
--   ID            INTEGER   PRIMARY KEY,
--   MEASURED      TEXT  NOT NULL,
--   VALUE         REAL  NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS CONFIG(
--   ID            INTEGER   PRIMARY KEY,
--   NAME          TEXT  NOT NULL,
--   VALUE         TEXT  NOT NULL
-- );

DROP TABLE IF EXISTS WATERING;

CREATE TABLE IF NOT EXISTS WATERING(
  ID            INTEGER   PRIMARY KEY,
  STARTED       TEXT  NOT NULL,
  ENDED         TEXT  NOT NULL
);

DROP TABLE IF EXISTS SCHEDULE;

CREATE TABLE IF NOT EXISTS SCHEDULE(
  ID            INTEGER   PRIMARY KEY,
  MONDAY        INTEGER DEFAULT 1,
  TUESDAY       INTEGER DEFAULT 1,
  WEDNESDAY     INTEGER DEFAULT 1,
  THURSDAY      INTEGER DEFAULT 1,
  FRIDAY        INTEGER DEFAULT 1,
  SATURDAY      INTEGER DEFAULT 1,
  SUNDAY        INTEGER DEFAULT 1,
  TIME          TEXT NOT NULL,
  ACTIVE        INTEGER DEFAULT 1,
  DURATION      INTEGER NOT NULL
);

-- INSERT INTO CONFIG (NAME, VALUE) VALUES ("MEASUREMENT_LIMIT", "300");
-- INSERT INTO CONFIG (NAME, VALUE) VALUES ("MEASUREMENT_CRON", "00 01 * * * *");
INSERT INTO SCHEDULE (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY, TIME, ACTIVE, DURATION) VALUES (1, 1, 0, 0, 1, 1, 0, "13:40", 1, 30);
INSERT INTO SCHEDULE (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY, TIME, ACTIVE, DURATION) VALUES (0, 0, 1, 1, 0, 0, 1, "14:30", 0, 15);